backend:
  name: git-gateway
  repo: nolafs/renaissance-website
media_folder: "site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
# publish_mode: editorial_workflow
site_url: https://eloquent-curran-2d10a7.netlify.com

collections:
  - name: "case-studies" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Case Studies" # Used in the UI, ie.: "New Post"
    folder: "site/content/case-studies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Project Type", name: "project", widget: "select", options: [
        {label: "Go-to-market", value: "GTM" },
        {label: "Go-to-market", value: "GTM" },
        {label: "Go-to-market", value: "GTM" },
        ]}
      - {label: "Client", name: "client", widget: "string", required: true}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "testimonials"
    label: "Testimonials"
    folder: "site/content/testimonials"
    create: true
    identifier_field: name
    fields:
      - {label: "Profile", name: "profile", widget: image}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Name", name: "name", widget: string}
      - {label: "Position", name: "position", widget: string}
      - {label: "Company", name: "company", widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Hero Image, name: hero_image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Services Section", name: services, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: text},
              {label: "Subheader", name: "subheader", widget: string},
              {label: "Services List", name: "services_list", widget: "list", fields: [
              {label: "Title" , name: "title" , widget: string},
              {label: "text" , name: "text" , widget: text},
              {label: "Icon" , name: "icon" , widget: image},
              ]}
          ]}
          - {label: "Clients Section", name: clients, widget: object, fields: [
             {label: "Heading", name: "heading", widget: string},
             {label: "Text", name: "text", widget: "text"},
             {label: "Clients Featured", name: "clients_featured", widget: "list", fields: [
             {label: "Name" , name: "company" , widget: "text"},
             {label: "Link" , name: "company_url" , widget: string},
             {label: "Logo" , name: "company_logo" , widget: image},
             ]},
             {label: "Clients", name: "clients", widget: "list", fields: [
             {label: "Name" , name: "company" , widget: "text"},
             {label: "Link" , name: "company_url" , widget: string},
             {label: "Logo" , name: "company_logo" , widget: image},
             ]}
          ]}
          - label: "Testimonial"
            name: "testimonial"
            widget: "relation"
            collection: "testimonials"
            searchFields: ["name", "company"]
            valueField: "name"
            displayFields: ["name", "company"]
          - {label: "Contact Section", name: contact, widget: object, fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "text", widget: "text"},
          ]}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Mission", name: mission, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}
          ]}
          - {label: "Values", name: values, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Heading", name: "heading", widget: string, default: "Our Values"},
              {label: "Text", name: "text", widget: "text"}
          ]}
          - {label: "Founder", name: founder, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Heading", name: "heading", widget: string, default: "About the Founder"},
              {label: "Founder Name", name: "founder_name", widget: string, default: "Stefano Petrullo"},
              {label: "Text", name: "text", widget: "markdown"}
          ]}
          - {label: "Team", name: team, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string, default: "The Team"},
              {label: "Text", name: "text", widget: "text"},
              {label: "Team Members", name: "team_list", widget: "list", fields: [
              {label: "Name" , name: "name" , widget: string},
              {label: "Position" , name: "position" , widget: text},
              {label: "Text" , name: "text" , widget: text},
              {label: "Image" , name: "image" , widget: image},
              ]}
          ]}
          - {label: "Why", name: why, widget: object, fields: [
            {label: "Heading", name: "heading", widget: string},
            {label: "Text", name: "text", widget: "text"},
            {label: "Why List", name: "why_list", widget: "list", fields: [
            {label: "Title" , name: "title" , widget: string},
            {label: "Text" , name: "text" , widget: text},
            {label: "Icon" , name: "icon" , widget: image},
            ]}
          ]}
      - file: "site/content/services/_index.md"
        label: "Services Page"
        name: "services"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Services", name: services, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: text},
              {label: "Subheader", name: "subheader", widget: string},
              {label: "Services List", name: "services_list", widget: "list", fields: [
              {label: "Title" , name: "title" , widget: string},
              {label: "text" , name: "text" , widget: text},
              {label: "Icon" , name: "icon" , widget: image},
              ]}
          ]}
          - {label: "Other Services", name: services, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: text},
              {label: "Subheader", name: "subheader", widget: string},
              {label: "Services List", name: "services_list", widget: "list", fields: [
              {label: "Title" , name: "title" , widget: string},
              {label: "text" , name: "text" , widget: text},
              ]}
          ]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Contact Information", name: services, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string, default: "Contact Information"},
              {label: "Telephone Numbers", name: "tel_list", widget: "list", fields: [
                {label: "tel" , name: "tel" , widget: string},
              ]},
              {label: "Emails", name: "email_list", widget: "list", fields: [
                {label: "Email" , name: "email" , widget: string},
              ]}
          ]}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/privacy/_index.md"
        label: "Privacy Page"
        name: "privacy"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/terms_conditions/_index.md"
        label: "Terms & Conditions Page"
        name: "terms_conditions"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
